#djangoproject/djangoproject/settings.py
"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

import environ
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = environ.Env()
print("Loading .env from:", os.path.join(BASE_DIR, ".env"))

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Print environment variables for debugging
print("DB_NAME:", env("DB_NAME", default="Not Set"))
print("DB_USER:", env("DB_USER", default="Not Set"))
print("DB_PWD:", env("DB_PASSWORD", default="Not Set"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = env('KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

X_FRAME_OPTIONS = 'ALLOW-FROM http://localhost:3000 http://127.0.0.1:8000 https://suganthan4444.github.io https://edu-gate.vercel.app https://edu-gate-suganthans-projects-822936bb.vercel.app'



ALLOWED_HOSTS = ['localhost', 'localhost:3000','127.0.0.1', 'https://suganthan4444.github.io', 'https://edu-gate.vercel.app', 'https://edu-gate-suganthans-projects-822936bb.vercel.app', '.vercel.app']

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [ "http://localhost:3000", 'http://127.0.0.1:3000', "https://suganthan4444.github.io", "https://edu-gate.vercel.app", "https://edu-gate-suganthans-projects-822936bb.vercel.app"] 
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]
CORS_ALLOW_HEADERS = [
    'content-type',
    'Authorization',
    'x-csrftoken',
]
CORS_ALLOW_CREDENTIALS = True

CSRF_USE_SESSIONS= True
CSRF_TRUSTED_ORIGINS=["http://localhost:3000", "https://suganthan4444.github.io", "https://edu-gate.vercel.app", "https://edu-gate-suganthans-projects-822936bb.vercel.app", "https://edu-gate-django.vercel.app"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'edugate_app',
    'corsheaders',
    'rest_framework',
    'rest_framework_swagger',
]


MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'edugate_app.middleware.CSRFTokenMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'edugatedjangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edugatedjangoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'edugate_app.validators.CustomPasswordValidator',
    },
    # Add other validators as needed
]

AUTHENTICATION_BACKENDS = [
    'edugate_app.backends.LearnerBackend',
    'edugate_app.backends.EducatorBackend',
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

TIME_ZONE = 'Asia/Kolkata' 
USE_TZ = True 
LANGUAGE_CODE = 'en-us'  



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  
EMAIL_USE_TLS = True  
EMAIL_HOST_USER = env('EMAIL_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_PASSWORD') 


import os

# Define the log file path
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Define the log file path
LOG_FILE = os.path.join(LOG_DIR, 'django.log')

# Logging settings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'educate_app': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Session engine (database-backed)
SESSION_COOKIE_AGE = 1209600  # Session expiration time in seconds (e.g., 20 minutes)
SESSION_COOKIE_NAME = 'sessionid'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_DOMAIN = None # Set to your domain if you need to share cookies across subdomains
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_PATH = '/'
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SESSION_COOKIE_SAMESITE = 'None'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

