# Generated by Django 5.0.3 on 2024-04-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educator_name', models.CharField(max_length=255)),
                ('educator_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=15, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_duration', models.DurationField()),
                ('course_thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('course_video_id', models.CharField(max_length=15, unique=True)),
                ('course_video', models.TextField()),
                ('course_exercise_id', models.CharField(max_length=15, unique=True)),
                ('course_exercise', models.TextField()),
                ('course_release_status', models.BooleanField(default=False)),
                ('course_rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=15)),
                ('course_name', models.CharField(max_length=100)),
                ('educator_id', models.CharField(max_length=100)),
                ('educator_name', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('course_duration', models.DurationField()),
                ('course_thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('course_video_id', models.CharField(max_length=15)),
                ('course_video', models.TextField()),
                ('course_exercise_id', models.CharField(max_length=15)),
                ('course_exercise', models.TextField()),
                ('course_completion_status', models.BooleanField(default=False)),
                ('course_certificate', models.FileField(blank=True, null=True, upload_to='course_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('educator_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('highest_qualification', models.CharField(max_length=100, verbose_name='Highest Qualification')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile_no', models.CharField(max_length=15, unique=True, verbose_name='Mobile Number')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='educator_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='educator_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField()),
                ('highest_qualification', models.CharField(max_length=100)),
                ('learner_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='learner_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='learner_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
