# Generated by Django 5.0.3 on 2024-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='educator_id',
            field=models.BigIntegerField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educatorcourses',
            name='course_exercise_id',
            field=models.BigIntegerField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='educatorcourses',
            name='course_id',
            field=models.BigIntegerField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='educatorcourses',
            name='course_video_id',
            field=models.BigIntegerField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='educatorcourses',
            name='educator_id',
            field=models.BigIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_id',
            field=models.BigIntegerField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learnercourses',
            name='course_exercise_id',
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='learnercourses',
            name='course_id',
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='learnercourses',
            name='course_video_id',
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='learnercourses',
            name='educator_id',
            field=models.BigIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='learnercourses',
            name='learner_id',
            field=models.BigIntegerField(max_length=100),
        ),
    ]
