# Generated by Django 5.0.3 on 2024-04-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0005_rename_course_exercise_educatorcourses_course_exercise_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorcourses',
            name='course_duration',
            field=models.TextField(),
        ),
    ]
