# Generated by Django 5.0.3 on 2024-04-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0006_alter_educatorcourses_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('educator_id', models.BigIntegerField()),
                ('educator_name', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('course_duration', models.CharField(max_length=100)),
                ('course_thumbnail_url', models.URLField()),
                ('course_video_url', models.URLField()),
                ('course_exercise_url', models.URLField()),
                ('course_price', models.CharField(max_length=100)),
            ],
        ),
    ]
