# Generated by Django 5.0.3 on 2024-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0007_releasedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorcourses',
            name='course_domain',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learnercourses',
            name='course_domain',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasedcourses',
            name='course_domain',
            field=models.TextField(null=True),
        ),
    ]
