# Generated by Django 5.0.3 on 2024-04-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0008_educatorcourses_course_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorcourses',
            name='course_delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educatorcourses',
            name='course_deletion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educatorcourses',
            name='course_reject_status',
            field=models.BooleanField(default=False),
        ),
    ]
