# Generated by Django 5.0.3 on 2024-05-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0009_educatorcourses_course_delete_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='educator_profile_pictures/'),
        ),
    ]
