# Generated by Django 5.0.3 on 2024-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0010_educator_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='mobile_no',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
