# Generated by Django 5.0.3 on 2024-05-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0012_remove_educatorcourses_id_remove_learnercourses_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnercourses',
            old_name='course_exercise',
            new_name='course_exercise_url',
        ),
        migrations.RenameField(
            model_name='learnercourses',
            old_name='course_completion_status',
            new_name='course_purchase_status',
        ),
        migrations.RemoveField(
            model_name='learnercourses',
            name='course_certificate',
        ),
    ]
