# Generated by Django 5.0.3 on 2024-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0013_rename_course_exercise_learnercourses_course_exercise_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercourses',
            name='course_duration',
            field=models.TextField(),
        ),
    ]
