# Generated by Django 5.0.3 on 2024-05-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0014_alter_learnercourses_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercourses',
            name='course_exercise_id',
            field=models.BigIntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='learnercourses',
            name='course_video_id',
            field=models.BigIntegerField(max_length=15, null=True),
        ),
    ]
