# Generated by Django 5.0.3 on 2024-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edugate_app', '0016_alter_learnercourses_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educatorcourses',
            name='course_delete_status',
        ),
        migrations.RemoveField(
            model_name='educatorcourses',
            name='course_deletion_reason',
        ),
    ]
